
package payment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Payment", targetNamespace = "http://payment.ws/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Payment {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://payment.ws/Payment/generatePaymentCodeRequest", output = "http://payment.ws/Payment/generatePaymentCodeResponse")
    public String generatePaymentCode(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://payment.ws/Payment/confirmPaymentRequest", output = "http://payment.ws/Payment/confirmPaymentResponse")
    public String confirmPayment(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://payment.ws/Payment/getPaidStatusRequest", output = "http://payment.ws/Payment/getPaidStatusResponse")
    public String getPaidStatus(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://payment.ws/Payment/doPaymentRequest", output = "http://payment.ws/Payment/doPaymentResponse")
    public boolean doPayment(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
